### DISCUSSION TITLE
Running target only when files (e.g from glob pattern) have changed

### DISCUSSION THREAD

**Discussion by IT-VBFK** [nuke-build/nuke#1098] [Q&A] [answered]
Hi

I am trying to achieve to do what github actions are doing with this configuration:

```yml
on:
  push:
    branches:
      - develop
    paths:
      - "docs/**/*"
  pull_request:
    branches:
      - develop
    paths:
      - "docs/**/*"
```

Meaning, that I want to run specific targets only when changes are detected.

Main goal is to avoid multiple build configurations (or workflow flies) in the repo. 

Now there is one workflow which runs a nuke build pipeline, but ignoring changes in the docs subfolder, and an other workflow that runs a spell check target (from NUKE), but this workflow is only watching for changes inside the docs folder.

The two example workflows

Docs spell check
```yml
on:
  push:
    branches:
      - develop
    paths:
      - "docs/**/*"
  pull_request:
    branches:
      - develop
    paths:
      - "docs/**/*"
...
```

General build pipeline
```yml
on:
  pull_request:
    paths-ignore:
      - docs/**
  push:
    paths-ignore:
      - docs/**
...
```
