### DISCUSSION TITLE
Get `github.event.pull_request.base.ref` from `GitHubActions.GitHubEvent`

### DISCUSSION THREAD

**Discussion by ITaluone** [nuke-build/nuke#1106] [Q&A] [answered]
Hi 

Have a quick question about how to retrieve the `github.event.pull_request.base.ref` inside the Build project.

`GitHubActions.GitHubEvent.GetPropertyStringValue("pull_request.base.ref")` seems a bit odd.

Or is there a way to generate 

```yml
env:
  var1: ${{ github.ref }}
  var2: ${{ github.run_number }}
  var3: ${{ github.event.pull_request.base.ref }}
```

with `GitHubActions` attribute?
