### DISCUSSION TITLE
Install multiple SDK versions

### DISCUSSION THREAD

**Discussion by ITaluone** [nuke-build/nuke#1108] [Q&A]
Hi 

Is it possible to install multiple SDK versions on a bare system?

Goal is to avoid adding the github actions yaml step `actions/setup-dotnet@v3` manually to the generated `continous.yml`.

Or take this a feature request for the possibility of something like that:

```csharp
[GitHubActions(
    name: "continous",
    GitHubActionsImage.WindowsLatest,
    InvokedTargets = new[] { nameof(A), nameof(B) },
    On = new[] { GitHubActionsTrigger.Push, GitHubActionsTrigger.PullRequest },
    FetchDepth = 0,
    WithSdks = new [] { "2.1.x", "3.1.x" } // <--- This thing here :)
)]
```
which generates:

```yml
- name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.1.x
          3.1.x
```

Thanks for this great piece of software :)
