### DISCUSSION TITLE
Fully customizable pipeline definitions

### DISCUSSION THREAD

**Discussion by KuraiAndras** [nuke-build/nuke#1230] [Show and tell]
I have encountered a number of projects where I had to customize pipelines in ways that the Nuke pipeline attributes could not handle. My usual solution would be to either manually write the pipeline or do some hacky workaround to generate a customized pipeline file.

I have been thinking and came up with a solution I would like to pursue, and I would like to get some critique before pushing forward (If I finish this then it will be open sourced). Keep in mind that I have mostly used nuke with GitHub Workflows and Azure Pipelines.

I like nuke's generated pipelines, but they have a few problems:
- No support for running on self-hosted runners
- No support for running inside containers
- Built-in steps might be behind on versions
- Sometimes the easiest and most sane solution is to have steps before you run nuke (my case was I needed to install cloudsmith)

So, I thought about making an alternative which gives you full control of the generated files.

The sample build we want to run:

```csharp
partial class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.Run);

    [Parameter("Configuration to build - Default is 'Debug' (local) or 'Release' (server)")]
    readonly Configuration Configuration = IsLocalBuild ? Configuration.Debug : Configuration.Release;

    Target SayHello => _ => _
        .Executes(() => Log.Information("Saying Hello"));

    Target Run => _ => _
        .Executes(() => Log.Information("Run completed, configuration is {Configuration}", Configuration));
}
```

Current generation parameters:

```csharp
[GitHubActions
(
    "ci",
    GitHubActionsImage.UbuntuLatest,
    FetchDepth = 0,
    OnPushBranches = new[] { "main" },
    CacheExcludePatterns = new[] { "*.tar" },
    InvokedTargets = new[] { nameof(Run), nameof(SayHello) }
)]
```

My approach:
```csharp
// We specify a factory type so we are not restricted to primitives
[GithubActionsExtended(typeof(Factory))]
partial class Build
{
    // Factpry is nested type, so we don't need to specify Build.SayHello and others
    public class Factory : IGithubActionsImplementationFactory
    {
        // Using the new target-typed new expressions helps a lot but it is a bit too verbose
        // Might be improved by terse formatting?
        public GithubWorkflowDefinition Create() => new()
        {
            FileName = "extended",
            Name = "extended",
            On = new()
            {
                Push = new()
                {
                    Branches = new[]
                    {
                        "main"
                    }
                }
            },
            Jobs = new()
            {
                { "ubuntu-latest", new()
                    {
                        Name = "ubuntu-latest",
                        RunsOn = "ubuntu-latest",
                        // Fully custom steps
                        Steps = new Step[]
                        {
                            new Checkout() { FetchDepth = 0 }, // Custom checkout step
                            new Cache() { CacheExcludePatterns = new[]{ "*.tar" } }, // Custom cache step
                            new Step(){ Run = "echo \"After\"" }, // Generun step
                            new NukeRun() { InvokedTargets = new[]{ nameof(Run), nameof(SayHello) } }, // cusrom step for running nuke
                            new Step(){ Run = "echo \"Before\"" }
                        },
                    }
                }
            }
        };
    }
}
```

Right now, this will produce the following output:
```yaml
# ------------------------------------------------------------------------------
# <auto-generated>
#
#     This code was generated.
#
#     - To turn off auto-generation set:
#
#         [GithubActionsExtended (AutoGenerate = false)]
#
#     - To trigger manual generation invoke:
#
#         nuke --generate-configuration GitHubActions --host GitHubActions
#
# </auto-generated>
# ------------------------------------------------------------------------------

name: extended
on:
  push:
    branches:
      - main
jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: >-
            .nuke/temp

            ~/.nuget/packages

            !*.tar
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - run: echo "After"
      - name: 'Run: Run SayHello'
        run: ./build.cmd Run SayHello
      - run: echo "Before"

```

Stuff that's missing but might be possible:
- Automatically handle targets with `.Produces()`
- Automatically import secrets from `.Requires()`
- Add all missing properties from GitHub 's documentation
- Supporting other providers - Azure, Jenkins, AppVeyor, etc...

So how does this work?
The basic idea is that surely GitHub workflows can be represented with simple POCOs which are then serialized to YAML. So the `GithubWorkflowDefinition` created by the factory will be serialized using tools provided by nuke's `ConfigurationAttributeBase`

some code from the implementation:
```csharp
public class GithubWorkflowDefinition
{
    [YamlIgnore]
    public required string FileName { get; init; }

    public required string Name { get; init; }
    public string? RunName { get; init; }

    public required On On { get; init; }

    public required Dictionary<string, Job> Jobs { get; init; }
}
public class Step
{
    [YamlMember(Order = int.MinValue)]
    public virtual string? Name { get; set; }
    [YamlMember(Order = int.MinValue + 1)]
    public virtual string? Uses { get; set; }
    [YamlMember(Order = int.MinValue + 2)]
    public virtual string? Run { get; set; }
    [YamlMember(Order = int.MinValue + 3)]
    public virtual Dictionary<string, object>? With { get; set; }
}
public class Checkout : Step
{
    [YamlIgnore]
    public string Version { get; init; } = "3";

    [YamlIgnore]
    public int? FetchDepth { get; init; }

    public override string? Uses => $"actions/checkout@v{Version}";

    public override Dictionary<string, object>? With => FetchDepth is null
        ? null
        : new()
        {
            { "fetch-depth", FetchDepth },
        };
}
public class NukeRun : Step
{
    [YamlIgnore]
    public required string[] InvokedTargets { get; init; }

    [YamlIgnore]
    public string RunCommand { get; init; } = "./build.cmd";

    public override string? Name => $"Run: {string.Join(' ', InvokedTargets)}";

    public override string Run => $"{RunCommand} {string.Join(' ', InvokedTargets)}";
}
```

Stuff that is not in scope:
- Making it 100% bulletproof. I do not plan on making this in a way which prohibits the user from making a faulty pipeline definition
- Making it terser/more beginner friendly than nuke's current implementation - if you like using the current way of generating pipeline definitions then keep using them. This would be for scenarios where more customization is needed, but you still want nuke to do some heavy lifting

I hope some of you might like this idea, so if you have some feedback, please share (even if you don't like this idea!)
