### DISCUSSION TITLE
Nuke and Azure Devops Microsoft Hosted Agent

### DISCUSSION THREAD

**Discussion by epsmae** [nuke-build/nuke#663] [Q&A]
I am trying to get nuke running on azure devops with a microsoft hostet agent.
The agents can switch between the jobs, this result in the error that the restore may is executed on a different agent than the compile and therefore the packages are missing.

May I missed something? I use these atributes:

```
[CheckBuildProjectConfigurations]
[ShutdownDotNetAfterServerBuild]
InvokedTargets = new[] { nameof(Clean), nameof(Restore), nameof(Compile), nameof(Test), nameof(Pack) })]
class Build : NukeBuild
...
```

Which generates the following pipline.yaml

```
stages:
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Clean
        displayName: 'Clean'
        dependsOn: [  ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Clean --skip'
      - job: Restore
        displayName: 'Restore'
        dependsOn: [ Clean ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Restore --skip'
      - job: Compile
        displayName: 'Compile'
        dependsOn: [ Restore ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Compile --skip'
      - job: Test
        displayName: 'Test'
        dependsOn: [ Compile ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Test --skip'
      - job: Pack
        displayName: 'Pack'
        dependsOn: [ Test ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Pack --skip'
```
