### ISSUE TITLE
With GitHub CI integration .Produces results in Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Simonl9l** [nuke-build/nuke#1040]
### Usage Information

NUKE Execution Engine version 6.2.1 (OSX,.NETCoreApp,Version=v6.0)

### Description

per GitHub/Artifact [documentation](https://www.nuke.build/docs/cicd/github-actions/#artifacts)

Adding ` .Produces(Solution.Directory / "**/*.zip")` results in `Object reference not set to an instance of an object.`

No other diagnostic information is displayed.

Additionally 
- there is now a [v3 ](https://github.com/actions/upload-artifact/releases/tag/v3.1.0) version this action.
- are there any plans to per `.Consumes` as a Target definition property given a overload with similar arguments to `.Produces`, generate a GitHub workflow step to generate a [actions/download-artifact@v3 ](https://github.com/actions/download-artifact) step in the workflow.

### Reproduction Steps

have `GitHubAction` configured

```C#
GitHubActions(
    "MyAction",
    GitHubActionsImage.UbuntuLatest,
    FetchDepth = 0,
    EnableGitHubToken = true,
    PublishArtifacts = true,
    ImportSecrets = new[]
    {
        nameof(AWS_ACCESS_KEY_ID),
        nameof(AWS_SECRET_ACCESS_KEY),
    },    
    OnPushBranches = new []{ "develop", "release/*", "main", "hotfix/*"},
    InvokedTargets = new[] { nameof(MyTarget) })]
```
add a `.Produces(Solution.Directory /  "**/*.zip")` to a Target specification.

### Expected Behavior

have it generate the expected GitHub workflow step

```
uses: actions/upload-artifact@v1
  with:
    name: packages
    path: output/**/*.zip
```

### Actual Behavior

raises error - `Object reference not set to an instance of an object.`

### Regression?

never tied to use before.

### Known Workarounds

none

**Comment by matkoch** [comment]
Value injection happens later in the process.. so you have to do something like...

```
AbsolutePath SlnDir => RootDirectory / "foobar";
```

**Comment by Simonl9l** [comment]
@matkoch thanks for the hints!

I have:

- an: `  AbsolutePath LambdasFolder => RootDirectory / "Lambdas";`
- and this Produces Specification: ` .Produces(LambdasFolder / "**/*.zip")`

I'm expecting:
```
      - uses: actions/upload-artifact@v1
        with:
          name: Lambdas
          path: Lambdas/**/*.zip
```
but am getting in the generated workflow:
```
      - uses: actions/upload-artifact@v1
        with:
          name: Lambdas
          path: Lambdas
```

Is seem to be ignoring the glob specification per [this](https://github.com/actions/upload-artifact#upload-using-a-wildcard-pattern) documentation - or is this a @v3 feature, and if so are there any plans to support it ?

Finally per above - are there any plans in the future roadmap, per the original issue above, to support [actions/download-artifact@v3](https://github.com/actions/download-artifact)? Are there any workarounds to this we can implement locally?

Thanks again!
