### ISSUE TITLE
Auto-generated `yaml` file does not have enclosed filter patterns for `OnPushTags`

### ISSUE THREAD

**Issue by Crauzer** [nuke-build/nuke#1126]
### Usage Information

6.3.0 / .NET 6 / .NET 6 / Windows 22H2

### Description

When creating a `GitHubActions` build with certain filter patterns for the `OnPushTags` property, the resulting patterns are not enclosed in the generated `.yaml` file.

This is a requirement [as per GitHub Actions documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)

### Reproduction Steps

Add this to the `GitHubActions` attribute and observe the generated yaml
```cs
OnPushTags = new[] { "[0-9]+.[0-9]+.[0-9]+", "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+", "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+" }
```

### Expected Behavior

```yaml
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/18646077/216853000-cc32c89f-f685-470c-be4b-986bce1cdc2f.png)

### Known Workarounds

Insert the quotes manually like so:
```cs
OnPushTags = new[]
{
    "\"[0-9]+.[0-9]+.[0-9]+\"",
    "\"[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+\"",
    "\"[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+\""
}
```

### Could you help with a pull-request?

No
