### ISSUE TITLE
Skip all targets does not work with environment variable

### ISSUE THREAD

**Issue by MichaeIDietrich** [nuke-build/nuke#1400]
### Usage Information

8.0.0 / 8.0.100 / net8.0 / Windows

### Description

Passing `NUKE_SKIP=""` as environment variable to Nuke won't skip any dependencies while in comparison using `--skip` command line parameter will skip all dependent targets.

This is because the `ParameterService` will parse `NUKE_SKIP=""` as array with a single empty string item, in contrast `--skip` will be parsed as empty array, which is needed to skip all dependent targets.

There seems to be no obvious syntax to express an empty array in an environment variable. 
So we could either define a special syntax for that (e.g. `[]`) or we special case empty string for skipping all dependent targets.

#### Context:

To give some better understanding why I'm struggling with that:
Currently `--skip` is a tri-state:
`--skip A+B` while skip dependent target `A` and `B`.
`--skip` will skip all dependent targets
` ` will not affect skipping

This is unfortunately hard to use in some environments, e.g. AzurePipelines, because you cannot use it with parameters such as
`- script: 'path/to/nuke MY_TARGET --skip ${{ parameters.skipTargets }} --foo 123 --bar 456'`, since now it is impossible to pass any valid value to make it not skip any target.

In Azure Pipelines it could done using conditional environment variables with something like this:
```yaml
- script: 'path/to/nuke MY_TARGET  --foo 123 --bar 456'
  env:
  ${{ parameters.skipAll }}
    NUKE_SKIP: '' # like '--skip', but unfortunately not working with Nuke :(
  ${{ ne( parameters.skipByName, '' ) }}
    NUKE_SKIP: '{{ parameters.skipByName }}' # works fine
```

I hope that makes the use case a bit clearer.
Just as an alternative idea, maybe it makes sense to introduce a second parameter to explicitly skip all dependencies, something like `--skip-all true/false`, so there is no need for `--skip` to be tri-state.
Precedence could be: `--skip-all true` > `--skip A+B+..` > `--skip-all false`

I can help with creating a pull request if we decide to fix or adjust this. :)

### Reproduction Steps

1. Define environment variable `NUKE_SKIP=""`
2. Run any Nuke with a dependent target.

### Expected Behavior

All dependent targets are skipped like when using `--skip`.

### Actual Behavior

No target is skipped, because the syntax is interpreted as empty string and no target will match that name, so no target is being skipped.

### Known Workarounds

Not when using environment variables, only when using the `--skip` command line parameter.

### Could you help with a pull-request?

Yes
