### ISSUE TITLE
Add possibility to set azure pipeline (build) name via attribute

### ISSUE THREAD

**Issue by swimmesberger** [nuke-build/nuke#1411]
### Description

See: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops for use-cases for custom azure build pipeline names.
In yaml it can be set via the "name" property like so:

```yaml
trigger:
  - main

name: '$(Date:yyyy.M.d).$(Rev:r)'

variables:
  - group: pipeline-variables

stages:
...
```

It would be nice to set it via the generation attribute too like so:
```csharp
[AzurePipelines(
    AzurePipelinesImage.UbuntuLatest,
    InvokedTargets = [nameof(Test)],
    BuildName = "$(Date:yyyy.M.d).$(Rev:r)",
    TriggerBranchesInclude = ["master"],
    AutoGenerate = false
)]
public class Build : NukeBuild {
...
}
```

### Could you help with a pull-request?

No
