### ISSUE TITLE
nuke does not install dotnet 9 if dotnet 8 is installed

### ISSUE THREAD

**Issue by BusHero** [nuke-build/nuke#1499]
### Usage Information

9.0.3/9.0.x, 

### Description

A nuke project using `dotnet 9` fails to build on a GitHub action using an agent(ex. `Ubuntu-latest`) with an older version of dotnet(ex. `dotnet 8`)

### Reproduction Steps

A repository with the minimal reproducible example.
[NukeBugWithDotnet9](https://github.com/BusHero/NukeBugWithDotnet9)

### Expected Behavior

nuke installs dotnet 9 and builds succesfully

### Actual Behavior

nuke fails to build

### Regression?

I didn't check. Probably?

### Known Workarounds

Use an github action to setup dotnet 9 manually
```yaml
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
```

### Could you help with a pull-request?

Yes
