### ISSUE TITLE
Support GitVersion.CommandLine.DotnetCore

### ISSUE THREAD

**Issue by ScarletKuro** [nuke-build/nuke#180]
Can you guys make example for GitLab CI, since i can't figure out how to make it work together with GitVersion.

**Comment by matkoch** [comment]
That’s rather a question for the guys over at https://github.com/GitTools/GitVersion. But maybe @arodus can help.

**Comment by arodus** [comment]
GitVersion depends on Mono and libgit so you have to make sure that both are availble in the image. 
You can check out [this dockerfile](https://github.com/arodus/docker-jenkins-slave-mono/blob/master/Dockerfile) or directly use it from [docker hub](https://hub.docker.com/r/arodus/docker-jenkins-slave-mono/), but be aware that it also contains the JDK cause it was made for running as a jenkins slave.
I just tested to build this repository on github with the following config and the build suceeded without any errors.

```yml
image:   arodus/docker-jenkins-slave-mono

stages:
  - test

debug:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: test
  script:
    - ./build.sh
```
