### ISSUE TITLE
GitHub Actions Trigger "pullrequest" is not a valid event name.

### ISSUE THREAD

**Issue by MikeBairdRocks** [nuke-build/nuke#409]
### Description
GitHubActionsTrigger not using EnumValue to generate yaml file.

### Steps to reproduce

1. Attribute in Build.cs:
```
[GitHubActions("Compile", 
  GitHubActionsImage.UbuntuLatest, 
  AutoGenerate = true, 
  On = new []{ GitHubActionsTrigger.PullRequest, GitHubActionsTrigger.Push },
  ImportGitHubTokenAs = nameof(GitHubToken),
  InvokedTargets = new []{ nameof(Compile) })]
```

### Relevant log output
Generates yaml:
```
name: Compile

on: [pullrequest, push]

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.cmd Compile'
        run: ./build.cmd Compile
        env:
            GitHubToken: ${{ secrets.GITHUB_TOKEN }}
```

`on: [pullrequest, push]` should be `on: [pull_request, push] `
