### ISSUE TITLE
Add support for dotnet-version in GitHub Actions

### ISSUE THREAD

**Issue by mbaumanndev** [nuke-build/nuke#482]
In GitHub Actions we can specify a SDK version to use when executing the action.

Is it possible to generate the proper yml section for the `setup-dotnet` according to what's in the `global.json` or specified manually in the `GitHubActionsAttribute` ?

```
- name: Setup .NET Core
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.201
```
