### ISSUE TITLE
Generating GitHub workflow script with detailed triggers does not produce valid YAML

### ISSUE THREAD

**Issue by patrickklaeren** [nuke-build/nuke#499]
**Following attribute:**
```cs
[GitHubActions("Test",
    GitHubActionsImage.WindowsLatest,
    OnPushBranches = new[] {"master"},
    InvokedTargets =
        new[]
        {
            nameof(Compile),
        })]
```

**Produces:**
```yml
on:
  push
    branches:
      - master
```

**should be**
```yml
on:
  push:
    branches:
      - master
```

as per GitHub Workflow schema https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration

Code site:

https://github.com/nuke-build/nuke/blob/9c8ebc11d555d9891a78246b76eba32267a225c5/source/Nuke.Common/CI/GitHubActions/Configuration/GitHubActionsVcsTrigger.cs#L23
