### ISSUE TITLE
Autogenerated Azure Pipeline stage names are invalid in some cases

### ISSUE THREAD

**Issue by nloum** [nuke-build/nuke#558]
### Description

The auto-generated `azure-pipelines.yml` uses stage names that are based on the image names, but if the image name contains a `.` then the stage name does also, and that is considered invalid by Azure Pipelines.

### Steps to reproduce

```
[AzurePipelines(
	AzurePipelinesImage.Ubuntu1804, // the enum value for this is "ubuntu-18.04"
	AutoGenerate = true,
	InvokedTargets = new[] { nameof(Test) })]
class Build : NukeBuild
{
 // ...
}
```

Here's the generated YAML file:

```
stages:
  - stage: ubuntu_18.04 # this is an invalid stage name right here
    displayName: 'ubuntu-18.04'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-18.04'
    jobs:
```

### Relevant log output

The error on Azure Pipelines happens when trying to trigger the build:

```
Stage ubuntu_18.04 has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.
```
