### ISSUE TITLE
Add ability to create multiple jobs in a single workflow

### ISSUE THREAD

**Issue by dansiegel** [nuke-build/nuke#953]
### Description

There are a number of scenarios where breaking a pipeline/workflow into various jobs makes a lot of sense. This could be to take advantage of parallel builds or simply to handle breaking up the CI Build into:
- Build
- Test
- Deploy Stage
- Deploy Production

Being able to more easily create these complex builds with Nuke would be extremely beneficial

### Usage Example

For a simple example we could look at the Prism.Maui Build workflow. In this example we build & test in one job, then run 2 parallel jobs to deploy to different NuGet feeds:

```yaml
jobs:
  build:
    # Build Library & Run Tests
  deploySponsorConnect:
    # Deploys artifacts to Sponsor Connect Feed
  deployInternal:
    # Deploys to internal dog food channel
```

A more complex but common scenario could be the following where we have an iOS/Android build which we want to run in parallel to shorten the build times. These may have additional jobs which depend on a previous job completing and require artifacts from the previous job(s):

```yaml
jobs:
  build-ios:
    # build iOS App
  build-android:
    # build Android App
  run-android-uitest:
    # Retrieve Android artifacts and run automated UI Tests
  run-ios-uitest:
    # Retrieve iOS artifacts and run automated UI Tests
  deploy-appcenter:
    # When both UI Tests have completed get all artifacts and deploy to App Center
  deploy:
    environment: Store
    # the CI host may have a manual approval and deploy to the store
```

An updated Build might look something like:

```cs
[GitHubActions("continuous",
    FetchDepth = 0,
    AutoGenerate = true,
    OnPushBranches = new[] { MasterBranch })]
[Job("android-build", GitHubActionsImage.MacOsLatest,
    ImportSecrets = new [] { AndroidKeyStoreB64, AndroidKeystoreName, AndroidKeystorePassword },
    InvokeTargets = new [] { BuildAndroid })]
[Job("ios-build", GitHubActionsImage.MacOsLatest,
    ImportSecrets = new [] { iOSP12B64, iOSP12Password },
    InvokeTargets = new [] { BuildIOS })]
[Job("appcenter", GitHubActionsImage.MacOsLatest,
    DependsOn = new [] { "android-build", "ios-build" },
    UsesArtifacts = new [] { "android-artifacts", "ios-artifacts" },
    InvokesTargets = new [] { AppCenterDeployIOS, AppCenterDeployAndroid })]
class Build : NukeBuild
{
}
```
